Jk 2023 08 14 newprayer
BetaMasaheft/Works pull request #1021
Opened 2023-08-14 11:38 UTC by karljonaskarlsson

Prayer work records created based on https://github.com/BetaMasaheft/Documentation/issues/2409

2023-08-14 12:23 UTC, thea-m commented on new/LIT6855Prayer.xml
> +                <title xml:lang="gez" xml:id="t1">Short prayer</title>
"en"
Could you give, either very briefly in the title or in the abstract, a short characterisation of the prayer's contents?

2023-08-14 12:23 UTC, thea-m commented on new/LIT6856PPHemamaBarya.xml
> +                <title xml:lang="gez" xml:id="t1">Prayer against Barya and Legewon</title>
Bāryā

2023-08-14 12:23 UTC, thea-m commented on new/LIT6856PPHemamaBarya.xml
> +                    <term key="Prayers"/>
Magic?

2023-08-14 13:43 UTC, thea-m requested changes
Thank you! ChristianContent is reserved for items that do not contain text, it should be ChristianLiterature here (see schema definitions).

2023-08-28 07:42 UTC, MassimoVilla requested changes
Thank you Jonas, I have just added few suggestions about text encoding. Please feel free to consider them

2023-08-28 07:42 UTC, MassimoVilla commented on new/LIT6856PPHemamaBarya.xml
> +                        ንድሃን፡ በሃይለ፡ ዝንቱ፡ አስማቲከ፡ አድኖ፡ ለገብርከ፡ ገብረ፡ እገሌ፡ እምባርያ፡ ወላጌዎን፡
perhaps አድ`<supplied reason="omitted">ኅ</supplied>`ኖ፡ ?

2023-08-28 07:42 UTC, MassimoVilla commented on new/LIT6858PPsnakes.xml
> +                        በስመ፡ አብ፡ ወወልድ፡ ወመን፡ ፈስ፡ ቅዱስ፡ ፩ አምላክ፨ አክዮስ፡ አክዮስ፡
ወመ`<surplus>ን፡</surplus>`ፈስ፡

2023-08-28 07:42 UTC, MassimoVilla commented on new/LIT6862PPscribe.xml
> +                            ክርስቶስ፡ አስተ፡ ፋጥን<supplied reason="undefined">፡</supplied>ወ<add place="above">አ</add>ስተ፡
`አስተ<surplus>፡</surplus>ፋጥን<supplied reason="undefined">፡</supplied>` 
`አስተ<surplus>፡</surplus>ቃንዕ፡`

2023-08-29 07:30 UTC, thea-m approved these changes

2023-08-29 08:22 UTC, MassimoVilla approved these changes

2023-08-29 08:22 UTC, merged