Lit6916 gadla eup
BetaMasaheft/Works pull request #1048
Opened 2024-01-30 20:31 UTC by MarcinKrawczuk

https://github.com/BetaMasaheft/Documentation/issues/2472

I would suggest to keep the English title as the main title, the Ge'ez one is not very 'title-like'...

2024-02-02 17:38 UTC, thea-m requested changes
Thank you, very nice! one minimal question

2024-02-02 17:38 UTC, thea-m commented on new/LIT6916GadlaEup.xml
> +                <title xml:lang="gez" type="normalized" corresp="#n2">Śǝna ḥǝywat wa-mǝgbār za-qǝddǝst wa-bǝḍʿǝt dǝngǝl ʾEwoṗarāksǝyā</title>
I would say bǝḍǝʿt

2024-02-02 20:05 UTC, MarcinKrawczuk commented
Of course!

pt., 2 lut 2024 o 18:38 thea-m ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Thank you, very nice! one minimal question
> ------------------------------
>
> In new/LIT6916GadlaEup.xml
> <https://github.com/BetaMasaheft/Works/pull/1048#discussion_r1476466084>:
>
> > @@ -0,0 +1,63 @@
> +<?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="LIT6916GadlaEup" xml:lang="en" type="work">
> +    <teiHeader>
> +        <fileDesc>
> +            <titleStmt>
> +                <title xml:lang="en" xml:id="t1">The life of St Euphrasia of Constantinople</title>
> +                <title xml:lang="gez" xml:id="n2">ሥነ ፡ ሕይወት፡ ወምግባር፡ ዘቅድስት፡ ወብፅዕት፡ ድንግል፡ ኤዎጰራክስያ፡</title>
> +                <title xml:lang="gez" type="normalized" corresp="#n2">Śǝna ḥǝywat wa-mǝgbār za-qǝddǝst wa-bǝḍʿǝt dǝngǝl ʾEwoṗarāksǝyā</title>
>
> I would say bǝḍǝʿt
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/1048#pullrequestreview-1859962558>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJQJ6TMM6QKZFFJVJYTYRUQAZAVCNFSM6AAAAABCR4S55KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNJZHE3DENJVHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-06 10:39 UTC, thea-m approved these changes

2024-02-06 10:40 UTC, merged