Addisie maftəḥe śǝrāy
BetaMasaheft/Works pull request #1056
Opened 2024-02-13 13:08 UTC by Addisie

2024-02-13 13:27 UTC, DenisNosnitsin1970 requested changes

2024-02-13 13:27 UTC, DenisNosnitsin1970 commented on 1001-2000/LIT1824Mafteh.xml
> +               <label>Prayer for Monday</label>
1) If you want to add a structure or text to a work record, you should take a full text witness (here, it  stops on Tuesday) in a way representative for the tradition. 
2) I have some doubts as to if the text is really structured according to the days of the week. I have never seen such a Meftahe seray. (if the means for this are notes in the upper margin, they do not necessarily reflect the structure)
3) Unless it is not done in one or another way, I suggest to add to LIT1824Mafteh the status of "general record". The collections with this title are of unstable composition, not much studied (possibly an issue can be done to discuss this).

2024-02-13 14:08 UTC, eu-genia commented on 1001-2000/LIT1824Mafteh.xml
> +            <note>The following text part description is based on the manuscript <ref type="mss" corresp="MEAG002"/>which is incomplete.</note>
I would not add edition here at all, use it just in the manuscript for now. Edition for text must be from an edited text or at least from a best witness. 




VERY VERY IMPORTANT: never ever use diacritics or any non-ASCII symbols in any file names, folder names, branch names, or xml:IDs. The name of this branch is a problem.

2024-02-16 20:55 UTC, eu-genia requested changes

2024-02-16 20:55 UTC, eu-genia commented on 1001-2000/LIT1824Mafteh.xml
>              <relation name="ecrm:CLP46i_may_form_part_of" active="LIT5139MagicPrayer" passive="LIT1824Mafteh"></relation>
`active `must always be the current record 

so relation should be `saws:contains` 

(or you can put the relation as it is now under `LIT5139MagicPrayer`)

2024-02-19 07:53 UTC, CarstenHoffmannMarburg approved these changes

2024-02-27 11:06 UTC, eu-genia commented on 1001-2000/LIT1824Mafteh.xml
>              <relation name="ecrm:CLP46i_may_form_part_of" active="LIT5139MagicPrayer" passive="LIT1824Mafteh"></relation>
(and added to LIT5139MagicPrayer)

that is 
either under LIT5139MagicPrayer we have the relation 
`<relation name="ecrm:CLP46i_may_form_part_of" active="LIT5139MagicPrayer" passive="LIT1824Mafteh"></relation>
`

or here in the LIT1824Mafteh record we have
` <relation name="saws:contains" active="LIT1824Mafteh" passive="LIT5139MagicPrayer"></relation>`

the current record is always the `active `member

2024-03-28 12:20 UTC, Addisie commented
All changes were carried out: https://github.com/BetaMasaheft/Works/pull/1065/files
                                               https://github.com/BetaMasaheft/Works/pull/1069

2024-03-28 12:20 UTC, closed without merging