Create LIT6934Edification
BetaMasaheft/Works pull request #1058
Opened 2024-02-15 07:08 UTC by CarstenHoffmannMarburg

I created a LIT record for a composition in BLorient8823 as recommended by Dorothea in https://github.com/BetaMasaheft/Documentation/issues/2482.

2024-02-15 08:11 UTC, eu-genia requested changes
very nice!

2024-02-15 08:11 UTC, eu-genia commented on new/LIT6934Edification.xml
> +                <title xml:lang="gez" xml:id="t1">Composition for moral edification</title>
en

2024-02-16 07:48 UTC, thea-m requested changes
Very nice

2024-02-16 07:48 UTC, thea-m commented on new/LIT6934Edification.xml
> +                    <term key="Philosophy"/>
I would say also ChristianLiterature

2024-02-16 08:20 UTC, merged