Create LIT for Amharic versions of Nagara Māryām and Maṣḥafa nuzāze
BetaMasaheft/Works pull request #1062
Opened 2024-02-23 08:30 UTC by CarstenHoffmannMarburg

I created two LIT records for the Amharic versions of Nagara Māryām and Maṣḥafa nuzāze according to our discussion in https://github.com/BetaMasaheft/Documentation/issues/2487.

2024-02-23 08:40 UTC, eu-genia requested changes

2024-02-23 08:40 UTC, eu-genia commented on new/LIT6937NagaraMarAmh.xml
> +                <title xml:lang="am" xml:id="t1">Nagara Māryām (Amharic)</title>
title in fidal
corresp for transcription

2024-02-23 08:40 UTC, eu-genia commented on new/LIT6938MasNuzazeAmh.xml
> +                <title xml:lang="gez" xml:id="t1">Maṣḥafa nuzāze (Amharic)</title>
lang="am"
title in fidel
corresp for transcription

2024-02-23 09:55 UTC, eu-genia approved these changes

2024-03-11 16:09 UTC, thea-m approved these changes

2024-03-11 16:10 UTC, merged