Create LIT6940Incarnation
BetaMasaheft/Works pull request #1064
Opened 2024-02-23 09:50 UTC by CarstenHoffmannMarburg

I created a record for an Amharic commentary in BLorient13223 and EMIP00269 as discussed in https://github.com/BetaMasaheft/Documentation/issues/2488.

2024-02-23 09:57 UTC, eu-genia requested changes

2024-02-23 09:57 UTC, eu-genia commented on new/LIT6940IncarnationAmh.xml
> +                    <relation name="lawd:hasAttestation" active="LIT6940IncarnationAmh" passive="BLorient2198"/>
we usually use the list of witnesses (`listWit `and `witness `under `sourceDesc`) for Works attested in Manuscripts

2024-02-23 09:57 UTC, eu-genia commented on new/LIT6940IncarnationAmh.xml
> +                <p/>
```
<listWit>
<witness corresp="BLorient2198"/>
<witness corresp="EMIP00269"/>
</listWit>
```

2024-02-26 09:32 UTC, eu-genia commented on new/LIT6940IncarnationAmh.xml
> +                <p>
you actually do not need the paragraph `p`

2024-02-26 09:47 UTC, DenisNosnitsin1970 reviewed
Could you please add translations to the Amharic titles?

2024-02-27 10:36 UTC, CarstenHoffmannMarburg commented
> Could you please add translations to the Amharic titles?

I propose: "The unity of God" and "The mysterious trinity and the unity of God"
What translations would you suggest?

Does the translated titly needs a type?

2024-02-27 10:52 UTC, DenisNosnitsin1970 commented
I would say, rumbling, 
t2 is "The Unity of Divinity and Humanity"
and t3 is "The Unity of the Mystery of Incarnation, Humanity and Divinity".

2024-02-27 11:20 UTC, DenisNosnitsin1970 approved these changes

2024-02-27 11:57 UTC, eu-genia approved these changes

2024-02-27 11:57 UTC, merged