Update LIT5905FidalaHawarya.xml
BetaMasaheft/Works pull request #1081
Opened 2024-04-11 15:37 UTC by thea-m

2024-04-11 22:45 UTC, eu-genia approved these changes

2024-04-15 07:38 UTC, CarstenHoffmannMarburg approved these changes

2024-04-15 07:52 UTC, CarstenHoffmannMarburg requested changes

2024-04-15 07:52 UTC, CarstenHoffmannMarburg commented on 5001-6000/LIT5905FidalaHawarya.xml
> +                <title xml:id="t3" xml:lang="en">1 John 1–7</title>
The First Epistle of John has 5 chapters according to my private Protestant Bible. If this refers to verses 1 to 7 of the first chapter, should it be 1 John 1:1-7? 
In LIT3509Epistle, the book is abbreviated "1 Joh."

2024-09-23 10:34 UTC, merged