Update LIT6936TarWaAmidBeta
BetaMasaheft/Works pull request #1132
Opened 2024-07-05 08:32 UTC by CarstenHoffmannMarburg

Minor updates to the names of several rulers.

2024-07-05 09:46 UTC, eu-genia requested changes

2024-07-05 09:46 UTC, eu-genia commented on 6001-7000/LIT6936TarWaAmidBeta.xml
> +                        <label>107th Generation - ʾAwgusṭos Qesār (Augustus Cesar)</label>
Caesar

2024-07-05 12:19 UTC, karljonaskarlsson approved these changes

2024-07-10 08:28 UTC, eu-genia approved these changes

2024-07-10 08:31 UTC, merged

2024-07-10 08:37 UTC, CarstenHoffmannMarburg commented
I wanted to merge this branch to the master, but apparently, it did not work out. What was wrong?

<img width="940" alt="Screenshot 2024_TarikaWA-jobs-failed" src="https://github.com/BetaMasaheft/Works/assets/40291787/4b561c3d-e3f9-4612-aa90-3e9d37244118">

2024-07-10 09:32 UTC, eu-genia commented
All ok