New work file for a litany
BetaMasaheft/Works pull request #1136
Opened 2024-07-09 12:57 UTC by LeonardBahr

Jonas and I created a new work file for a little known or unknown liṭon prayer.

2024-07-09 13:11 UTC, karljonaskarlsson approved these changes

2024-07-10 07:39 UTC, CarstenHoffmannMarburg approved these changes

2024-07-10 08:25 UTC, eu-genia requested changes

2024-07-10 08:25 UTC, eu-genia commented on new/LIT7016Liton.xml
> +                <title xml:lang="gez" xml:id="t1">Liṭon wa‐kāʿba nāstabaqqʷǝʿo la‐ʾǝgziʾabǝḥer ʾabuhu</title>
It should be
```
<title xml:lang="gez" xml:id="t1">ሊጦን፡ ....</title>
<title xml:lang="gez" type="normalized" corresp="#t1">Liṭon wa‐kāʿba nāstabaqqʷǝʿo la‐ʾǝgziʾabǝḥer ʾabuhu</title>
<title xml:lang="en" corresp="#t1">your translation here</title>
```

2024-07-11 06:32 UTC, CarstenHoffmannMarburg approved these changes

2024-09-20 12:04 UTC, LeonardBahr commented
@eu-genia Since I carried out the changes, could you please merge this? Thank you in advance.

2024-09-20 12:07 UTC, eu-genia approved these changes

2024-09-20 12:09 UTC, merged