Created records for Amharic commentaries
BetaMasaheft/Works pull request #1139
Opened 2024-07-10 09:42 UTC by CarstenHoffmannMarburg

Created records for Amharic commentaries on the Kidān za-nagh and the Tǝmhǝrta ḫǝbuʾat as discussed in https://github.com/BetaMasaheft/Documentation/issues/2565.

2024-07-10 11:05 UTC, eu-genia requested changes

2024-07-10 11:05 UTC, eu-genia commented on new/LIT7023CommKidanTemHeb.xml
> +                    <relation name="saws:isCommentOn" active="#LIT7023CommKidanTemHeb" passive="LIT1716Kidanz"/>
remove `#`

2024-07-10 11:05 UTC, eu-genia commented on new/LIT7024CommKidanZaNagh.xml
> +                <title xml:lang="gez" xml:id="t1">Amharic commentary on the Kidān za-nagh</title>
en

2024-07-10 11:05 UTC, eu-genia commented on new/LIT7025CommTemHeb.xml
> +                <title xml:lang="gez" xml:id="t1">Amharic commentary on the tǝmhǝrta ḫǝbuʾāt</title>
`en`
Tǝmhǝrta

2024-07-10 11:05 UTC, eu-genia commented on new/LIT7023CommKidanTemHeb.xml
> +                    <witness corresp="#BLorient11719"/>
remove `#`

2024-07-10 11:05 UTC, eu-genia commented on new/LIT7024CommKidanZaNagh.xml
> +                    <witness corresp="#BLorient11719"/>
remove `#`

2024-07-10 11:05 UTC, eu-genia commented on new/LIT7025CommTemHeb.xml
> +                    <witness corresp="#BLorient11719"/>
remove `#`

2024-07-11 11:17 UTC, karljonaskarlsson approved these changes

2024-07-11 13:56 UTC, merged