Create LIT7042PrayerMichael
BetaMasaheft/Works pull request #1157
Opened 2024-07-27 06:27 UTC by CarstenHoffmannMarburg

Do not mind the strange name of the file! I was confused for a moment. This record is about Legewon.

2024-07-29 12:55 UTC, karljonaskarlsson requested changes

2024-07-29 12:55 UTC, karljonaskarlsson commented on new/LIT7042PrayerMichael.xml
> +                <ab>በስመ፡ <gap reason="ellipsis"/> ጸሎት፡ በእንተ፡ ሌጌዎን፡ ርኩስ፡ ዘይስልብ፡ ልበ፡ ሰብእ፡ ወያጸልም፡ አዕይንተ፡</ab>
ይሰልብ፡ ?

2024-08-05 13:22 UTC, karljonaskarlsson approved these changes

2024-09-23 10:39 UTC, eu-genia approved these changes
OK, maybe **after** the merge you can rename and delete "Michael" from the filename and xml:id, just leave LIT7042Prayer as the ID, thank you

2024-09-23 10:39 UTC, merged

2024-09-23 10:46 UTC, CarstenHoffmannMarburg commented
> OK, maybe **after** the merge you can rename and delete "Michael" from the filename and xml:id, just leave LIT7042Prayer as the ID, thank you

OK. When I understand you correctly, I shall change the name of the file in a new branch and pull request and change the ms record accordingly.