Create LIT7049Aqweyasat.xml
BetaMasaheft/Works pull request #1168
Opened 2024-08-28 08:15 UTC by CarstenHoffmannMarburg

According to our discussion in https://github.com/BetaMasaheft/Documentation/issues/2601.

2024-08-28 21:57 UTC, DenisNosnitsin1970 requested changes

2024-08-28 21:57 UTC, DenisNosnitsin1970 commented on new/LIT7049Aqweyasat.xml
> +                <title xml:lang="gez" xml:id="t1">ለአቍያጻት፡ አንተ፡ ባርያ፡ ጸሊም፡ ጋኔን፡ ህሡም፡ </title>
No space at the end.

2024-08-28 21:57 UTC, DenisNosnitsin1970 commented on new/LIT7049Aqweyasat.xml
> +                <title xml:lang="gez" xml:id="t1">ለአቍያጻት፡ አንተ፡ ባርያ፡ ጸሊም፡ ጋኔን፡ ህሡም፡ </title>
The wording in the incipit as supplied by the catalogue is a a little strange; 
I assume ለአቍያጻት፡ probably builds a nomilal construction with the preceding word, ወመላኪሆሙ፡. Not to break the sense (?) may be it is better to provide as a title just: ʾAnta Bāryā ṣallim gānen hǝśśum ...

2024-08-29 11:39 UTC, eu-genia approved these changes

2024-08-29 12:06 UTC, DenisNosnitsin1970 requested changes

2024-08-29 12:06 UTC, DenisNosnitsin1970 commented on new/LIT7049Aqweyasat.xml
> +                <title xml:lang="en" corresp="#t1">You, black Bāryā, bad demon (…)</title>
I think we do not need brackets around multiple dots.

2024-10-24 12:24 UTC, merged