Create LIT7050SerataKrestiyan.xml
BetaMasaheft/Works pull request #1169
Opened 2024-08-28 09:46 UTC by CarstenHoffmannMarburg

According to our discussion in https://github.com/BetaMasaheft/Documentation/issues/2549.

2024-08-28 10:03 UTC, DenisNosnitsin1970 requested changes

2024-08-28 10:03 UTC, DenisNosnitsin1970 commented on new/LIT7050SerataKrestiyan.xml
> +                <language ident="gez">Gǝʿǝz</language>
Insert here also Amharic.

2024-08-28 12:50 UTC, DenisNosnitsin1970 approved these changes

2024-08-29 11:46 UTC, eu-genia approved these changes

2024-08-29 11:47 UTC, merged