Create LIT7056Qene.xml
BetaMasaheft/Works pull request #1176
Opened 2024-08-31 16:37 UTC by CarstenHoffmannMarburg

I assume, that it is of the Śǝllāse type, because I counted six verses (I took line 3 as one and did not divide it into two, because the rhyme word ግብጽ is expunctuated (because infact it does not make sense to me in this place) and is not followed by a verse-marker (።) 

I am not sure about the translation of the title, i.e. whether I have put the title words in a sensitive and grammatically correct order.

I have seen, that the Qǝne-type and keyword Śǝllāse is written without a dash on the a i.e. Śǝllase. I think this is incorrect and should be corrected. In Guidi 1901 it is given as ሥላሴ፡

<img width="245" alt="Screenshot 2024_Sellase" src="https://github.com/user-attachments/assets/20b980e2-a81b-46fe-89c4-2ac60ccddd72">

2024-09-23 10:32 UTC, eu-genia approved these changes

2024-09-23 11:41 UTC, karljonaskarlsson requested changes
It's a pleasure to get to look at these qǝne poems! :)

2024-09-23 11:41 UTC, karljonaskarlsson commented on new/LIT7056Qene.xml
> +                    <l n="4">ዳእሙ፡ ንብሎሙ፡ ፩ሰብአ፡ ሕ<add place="above">ፅ</add>ፅ።</l>
I think what has been added above is a ፀ

2024-09-23 11:41 UTC, karljonaskarlsson commented on new/LIT7056Qene.xml
> +                    <l n="5">መዋቲ፡ መትሩ፡ በሰይፈ፡ ተግሣጽ።</l>
I read መዋቴ

2024-09-23 11:41 UTC, karljonaskarlsson commented on new/LIT7056Qene.xml
> +                    <l n="6">ወሰቁለ፡ ሰቀሉ፡ በዕፅ። ።</l>
I read ወስቁለ

2024-09-23 11:41 UTC, karljonaskarlsson commented on new/LIT7056Qene.xml
> +                <title xml:lang="en" corresp="#t1">When Peter listened to the sweet voice of the crucified Christ ...</title>
ጥዑመ፡ ቃል፡ is an adjective, I believe, so I would translate: 

When Peter listened to the sweet-voiced crucified Christ…

2024-09-24 11:21 UTC, karljonaskarlsson approved these changes

2024-09-25 20:45 UTC, DenisNosnitsin1970 requested changes

2024-09-25 20:45 UTC, DenisNosnitsin1970 commented on new/LIT7056Qene.xml
>                      <l n="3">ወኢንበሎሙ፡ ለ<add place="above">ሰብእ</add><del rend="expunctuated">ግብጽ</del>፡ ዘሮሜ፡ ቀተልት፡ ሕያዋን፡ አብያጽ።</l>
ቀተልተ

2024-10-24 12:25 UTC, merged