Create LIT7067Qene.xml
BetaMasaheft/Works pull request #1187
Opened 2024-09-09 08:56 UTC by CarstenHoffmannMarburg

2024-09-09 18:29 UTC, eu-genia approved these changes

2024-09-09 20:02 UTC, DenisNosnitsin1970 requested changes

2024-09-09 20:02 UTC, DenisNosnitsin1970 commented on new/LIT7067Qene.xml
> +                <title xml:lang="en" corresp="#t1">Let us be saturated in each year from your offspring, daughter of Kephas (?) …</title>
Let us be saturated, year after year,

2024-09-11 13:43 UTC, karljonaskarlsson commented on new/LIT7067Qene.xml
> +                <title xml:lang="gez" corresp="#t1" type="normalized">Nǝṣgab lalla-ʿāmatu wallata kefā ʾǝm-daqiqǝki (Qǝne of the śǝllāse-type)</title>
It's lalla- according to Leslau, but maybe there are other sources that say it should not be geminated

2024-09-11 17:28 UTC, CarstenHoffmannMarburg commented on new/LIT7067Qene.xml
> +                <title xml:lang="gez" corresp="#t1" type="normalized">Nǝṣgab lalla-ʿāmatu wallata kefā ʾǝm-daqiqǝki (Qǝne of the śǝllāse-type)</title>
I think, we should be consistent with other Bm records. LIT3575Mashaf has lalla- and also zazza- in the title. I do not find any record, in which ለለ is transcribed with lala-.

2024-09-11 19:54 UTC, DenisNosnitsin1970 commented on new/LIT7067Qene.xml
> +                <title xml:lang="gez" corresp="#t1" type="normalized">Nǝṣgab lalla-ʿāmatu wallata kefā ʾǝm-daqiqǝki (Qǝne of the śǝllāse-type)</title>
Indeed. It is a bit strange, but let it be. I do not think it has a good morphological explanation, in his dictionary there is a number of strange geminations.

2024-09-11 19:55 UTC, merged