LIT7068 69
BetaMasaheft/Works pull request #1190
Opened 2024-09-12 12:31 UTC by DenisNosnitsin1970

Two qenes from Abb 145. LIT7069ItyopyaAbbay "Ityopya..." seems to be known and included into an Ethiopian printed collection of qenes, still to be found (perhaps it is in the sizable three volume "Ya-geez qeneyat"). Some excerpts from the prints, including the qene in question, can be found in GitHUb:  `https://github.com/geezorg/ebooks/blob/master/amharic/poetry/Miscellaneous/src/GeezQineyat`. Should it be included this source into bibliography?

2024-09-12 13:43 UTC, CarstenHoffmannMarburg requested changes

2024-09-12 13:44 UTC, CarstenHoffmannMarburg commented
> Some excerpts from the prints, including the qene in question, can be found in GitHUb: `https://github.com/geezorg/ebooks/blob/master/amharic/poetry/Miscellaneous/src/GeezQineyat`. Should it be included this source into bibliography?

If it is this text, it should be included.

2024-09-12 13:52 UTC, DenisNosnitsin1970 commented on new/LIT7068Emazatekat.xml
> +                <title xml:lang="gez" type="normalized" corresp="#t1">ʾƎma za-tǝkāt sakabki gola ʾalḥǝmt (Qǝne of kʷǝllǝkǝmu type)</title>
Yes.

2024-09-12 13:52 UTC, DenisNosnitsin1970 commented on new/LIT7068Emazatekat.xml
> +                        <note>The text is taken from <ref type="mss" corresp="BNFabb145"/>, fol. 56vc (division into verses is indicated with the four dot asterisk ።; the end of the poem is indicated
I think it is not necessary to encode it as "foreign". To make it searchable, somehow, there should be a term for this.

2024-09-12 14:10 UTC, karljonaskarlsson requested changes

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7068Emazatekat.xml
> +                            <l n="2"><supplied reason="undefined" resp="DN">አ</supplied>ጥር፡ ብኪ፡ ተዋርዶተ፡ ቤቴል፡ <supplied reason="undefined" resp="DN">ፃማ፡</supplied></l>
I read ኢ, but anything is fine, of course

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7068Emazatekat.xml
> +                            <l n="6">እመኔኪ፡ መንገለ፡ ሰም<supplied reason="undefined" resp="DN">ዑ</supplied>፡ ጽራኃ፡ መላእክት፡ በዜማ።</l>
እምኔኪ

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7068Emazatekat.xml
> +                            <l n="7">ወእ<supplied reason="undefined" resp="DN">መኔ</supplied>ሃ፡ መንገለ፡ ሰምዑ፡ ጽራኃ፡ ወ<gap reason="illegible" unit="chars" quantity="2"/>ት፡ እለ፡ በግርማ።</l>
maybe supply so that it reads ወራዙት

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7068Emazatekat.xml
> +                            <l n="8">አኮኑ፡ ሥላሴ፡ <gap reason="illegible" unit="chars" quantity="2"/> ዝነሙ፡ ከመ፡ ዓቅምኪ፡ ወዓ<gap reason="illegible"  unit="chars" quantity="3"/>፡ ለኪ፡ መና።</l>
`ወዓቅ<gap reason="illegible"`, no?

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7069ItyopyaAbbay.xml
> +                    <note>The text is taken from <ref type="mss" corresp="BNFabb145"/>, fol. 56vc
56vb–56vc

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7069ItyopyaAbbay.xml
> +                <title xml:lang="gez" xml:id="t1">ኢትዮጵያ፡ ዓባይ፡ እምኢትዮጵያ፡ በጦመረ፡ ወይሌ፡ ወላህ፡</title>
በጦማረ፡

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7069ItyopyaAbbay.xml
> +                        <l n="1">ኢትዮጵያ፡ ዓባይ፡ እምኢትዮጵያ፡ በጦመረ፡ ወይሌ፡ ወላህ፡ ዘደመ፡ ዕጕስታር፡ ቀለሙ።</l>
በጦማረ፡

2024-09-12 14:10 UTC, karljonaskarlsson commented on new/LIT7069ItyopyaAbbay.xml
> +                        <l n="5">እስመ፡ ዜና፡ ሞቱ፡ ተስምዓ፡ ቅድመ፡ ይትአምር፡ ሕማሙ።</l>
I read ተሰምዓ፡ and ይትአመር፡

2024-09-12 16:01 UTC, DenisNosnitsin1970 commented on new/LIT7069ItyopyaAbbay.xml
> +                        <l n="5">እስመ፡ ዜና፡ ሞቱ፡ ተስምዓ፡ ቅድመ፡ ይትአምር፡ ሕማሙ።</l>
yes indeed.

2024-09-12 16:01 UTC, DenisNosnitsin1970 commented on new/LIT7069ItyopyaAbbay.xml
> +                        <l n="1">ኢትዮጵያ፡ ዓባይ፡ እምኢትዮጵያ፡ በጦመረ፡ ወይሌ፡ ወላህ፡ ዘደመ፡ ዕጕስታር፡ ቀለሙ።</l>
ok

2024-09-12 16:09 UTC, DenisNosnitsin1970 commented
Thank you for corrects! I discovered one of the qenes elsewhere.

2024-09-13 11:18 UTC, karljonaskarlsson approved these changes

2024-09-13 19:44 UTC, merged