2024 09 27 jk qene effo
BetaMasaheft/Works pull request #1219
Opened 2024-09-30 12:31 UTC by karljonaskarlsson

Another qene from the Uppsala collection. This is interesting, because it has two attestations in the manuscript: once on a loose leaf and once in the hand of the main scribe (= Kolmodin?). I follow the readings of the loose leaf: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0457&pid=alvin-record:280997

There is a word in the first line that I can't make out, so ideas would be appreciated!

2024-09-30 12:41 UTC, eu-genia commented on new/LIT7078QeneEffo.xml
> +                <p><foreign xml:lang="gez">Mawaddəs</foreign>-type <foreign xml:lang="gez">qǝne</foreign>
`ref type="authFile" corresp="Mawaddes"` or add to keywords?

2024-09-30 12:41 UTC, eu-genia commented on new/LIT7078QeneEffo.xml
> +                    <witness corresp="UppQ1524o"/>
In this case, to make the particularity more visible, I would list two wtnesses 
```
<witness corresp="UppQ1524o">Uppsala, Q 1524o, f. 30-31</witness>
<witness corresp="UppQ1524o">Uppsala, Q 1524o, f. 43</witness>
```

2024-09-30 13:00 UTC, nafisa-valieva approved these changes

2024-09-30 19:47 UTC, CarstenHoffmannMarburg requested changes

2024-10-01 12:28 UTC, karljonaskarlsson commented on new/LIT7078QeneEffo.xml
> +                <title xml:lang="gez" xml:id="t1">እፎ፡ አይሁድ፡ አዝማደ፡ እምከ፡ <surplus resp="JK">ተ</surplus>ደብተራ፡ መስቀል፡ ተከሉ፡ በአውደ፡ መትከፍትከ፡ ሴሎ።</title>
Thanks! :)

2024-10-01 12:29 UTC, karljonaskarlsson commented on new/LIT7078QeneEffo.xml
> +                <title xml:lang="en" corresp="#t1">How (could) the Jews, the relatives of your mother, the Tabernacle, plant the Cross in the courtyard of your shoulders, Selo…</title>
I don't know if "around" makes much more sense, but I can change it :)

2024-10-01 13:08 UTC, CarstenHoffmannMarburg approved these changes

2024-10-17 08:15 UTC, merged