2024 10 04 jk qene tawa
BetaMasaheft/Works pull request #1229
Opened 2024-10-04 09:29 UTC by karljonaskarlsson

Another qene from Uppsala: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0342&pid=alvin-record:280997

2024-10-07 09:07 UTC, CarstenHoffmannMarburg requested changes

2024-10-07 09:07 UTC, CarstenHoffmannMarburg commented on new/LIT7088QeneTawa.xml
> +                    <l n="4">ወአፃ<choice resp="JK"><sic>ቢ</sic><corr>ብ</corr></choice><choice resp="JK"><sic>እ</sic><corr>ኢ</corr></choice>ቢእከ፡
Perhaps it is easier for the user to get it, if you have one sic and one corr for both letters: 
`ወአፃ<choice resp="JK"><sic>ቢእ</sic><corr>ብኢ</corr></choice>ከ፡`

One ቢእ following the markup is redundant in the end of the line.

2024-10-10 13:05 UTC, karljonaskarlsson commented on new/LIT7088QeneTawa.xml
> +                <title xml:lang="en" corresp="#t1">Little calf, Saviour of the World, whose foot the Shepherd of Beasts, the nail(s), bound…</title>
Ok, I'm not sure

2024-10-10 13:38 UTC, CarstenHoffmannMarburg approved these changes

2024-10-10 14:30 UTC, merged