2024 10 04 jk qene mamer
BetaMasaheft/Works pull request #1238
Opened 2024-10-11 12:26 UTC by karljonaskarlsson

This is clearly some kind of poetic composition, but it appears not to be rhymed, so I'm not sure if it can be classified as a qene in the strict sense. It's from the same manuscript as the rest of the Uppsala qene, with images here: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0310&pid=alvin-record:280997

2024-10-11 13:31 UTC, nafisa-valieva approved these changes
very interesting! were they impessed by him really or they are flirting? :-)

2024-10-11 14:10 UTC, eu-genia requested changes

2024-10-11 14:10 UTC, eu-genia commented on new/LIT7092QeneMamer.xml
> +                <title xml:lang="gez" corresp="#t1" type="normalized">Māʾmǝr wa-labbāwi bǝʿse ʾƎgziʾabǝḥer</title>
No mark up in title

2024-10-11 14:10 UTC, eu-genia commented on new/LIT7092QeneMamer.xml
> +                    of <persName ref="PRS14576AndersSvensson"/> (called <foreign xml:lang="gez">ቄስ፡ ሜንሶን፡</foreign>).</p>
in honour of (delete the)

2024-10-11 14:21 UTC, karljonaskarlsson commented on new/LIT7092QeneMamer.xml
> +                <title xml:lang="gez" corresp="#t1" type="normalized">Māʾmǝr wa-labbāwi bǝʿse ʾƎgziʾabǝḥer</title>
Sorry, thank you!

2024-10-11 16:08 UTC, eu-genia approved these changes

2024-10-14 10:31 UTC, CarstenHoffmannMarburg approved these changes

2024-10-16 21:45 UTC, merged