Lit7141 story
BetaMasaheft/Works pull request #1319
Opened 2024-11-13 21:09 UTC by MarcinKrawczuk

https://github.com/BetaMasaheft/Documentation/issues/2685

Just a very basic record because I have no idea what this text is :(

2024-11-14 09:24 UTC, CarstenHoffmannMarburg commented
> Just a very basic record because I have no idea what this text is :(

Yes, it is legitimate to keep it basic. Me too, I have no idea, what this place name is about and what kind of text it could be.

2024-11-14 09:26 UTC, CarstenHoffmannMarburg requested changes

2024-11-14 09:26 UTC, CarstenHoffmannMarburg commented on new/LIT7141Story.xml
> +                <title xml:lang="gez" type="normalized" corresp="#t2">Zenāhu la-waldu nǝguś za-daseta Nāmulāʼas</title>
Transcription and fidal must be identical. Either ናሙላአስ፡ = Nāmulāʾas or ናሚላአስ፡ Nāmilāʾas
End fidal with ፡
Use proper transcription sign ʾ for Aleph.

2024-11-14 19:29 UTC, MarcinKrawczuk commented
Done!

czw., 14 lis 2024 o 10:27 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In new/LIT7141Story.xml
> <https://github.com/BetaMasaheft/Works/pull/1319#discussion_r1841843548>:
>
> > @@ -0,0 +1,57 @@
> +<?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="LIT7141Story" xml:lang="en" type="work">
> +    <teiHeader>
> +        <fileDesc>
> +            <titleStmt>
> +                <title xml:lang="en" xml:id="t1">Story of the son of the king of the island of Nāmulāʼas</title>
> +                <title xml:lang="gez" xml:id="t2">ዜናሁ፡ ለወልዱ፡ ንጉሥ፡ ዘደሴተ፡ ናሚላአስ</title>
> +                <title xml:lang="gez" type="normalized" corresp="#t2">Zenāhu la-waldu nǝguś za-daseta Nāmulāʼas</title>
>
> Transcription and fidal must be identical. Either ናሙላአስ፡ = Nāmulāʾas or
> ናሚላአስ፡ Nāmilāʾas
> End fidal with ፡
> Use proper transcription sign ʾ for Aleph.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/1319#pullrequestreview-2435480173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJXGJBJSEYZUPNLGOBL2ARUGNAVCNFSM6AAAAABRXNH3DSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZVGQ4DAMJXGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-15 09:35 UTC, CarstenHoffmannMarburg approved these changes

2024-11-15 09:51 UTC, merged