Lit17149 life
BetaMasaheft/Works pull request #1324
Opened 2024-11-19 19:09 UTC by MarcinKrawczuk

2024-11-19 19:31 UTC, CarstenHoffmannMarburg approved these changes

2024-11-19 19:31 UTC, CarstenHoffmannMarburg requested changes

2024-11-19 19:31 UTC, CarstenHoffmannMarburg commented on new/LIT17149Life.xml
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="LIT14519Life" xml:lang="en" type="work">
xml:id must correspond to file name.

2024-11-19 19:38 UTC, MarcinKrawczuk commented
I was instructed to simply rename the file (I have corrected the xml:id),
so the proper file name is LIT7149Life

wt., 19 lis 2024 o 20:33 Carsten Hoffmann ***@***.***>
napisał(a):

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In new/LIT17149Life.xml
> <https://github.com/BetaMasaheft/Works/pull/1324#discussion_r1848955002>:
>
> > @@ -0,0 +1,77 @@
> +<?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="LIT14519Life" xml:lang="en" type="work">
>
> In any case, the CAe has an extraordinary high number again. I think, this
> must be solved manually by @eu-genia <https://github.com/eu-genia> .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/1324#discussion_r1848955002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJWOJDMPX7UIEADRN5L2BOHCJAVCNFSM6AAAAABSC3F77GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBWGQ4DONJSGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-19 20:29 UTC, eu-genia commented
the file name should indeed be LIT7149Life. careful now it is 17149 instead of 7149

the file and the xml:id should be the same, 7149

2024-11-19 21:25 UTC, MarcinKrawczuk commented
Oh, now I see that the file name was wrong in my GitHub folder... Sorry
about that. I have renamed it.

wt., 19 lis 2024 o 21:30 Eugenia ***@***.***> napisał(a):

> the file name should indeed be LIT7149Life. careful now it is 17149
> instead of 7149
>
> the file and the xml:id should be the same, 7149
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/1324#issuecomment-2486688221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJXCXTY4THPYWTZEXPL2BONVZAVCNFSM6AAAAABSC3F77GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBWGY4DQMRSGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-20 09:42 UTC, CarstenHoffmannMarburg approved these changes

2024-11-20 18:59 UTC, merged