Nv corrections on ewostatewos
BetaMasaheft/Works pull request #1370
Opened 2024-12-30 12:10 UTC by nafisa-valieva

Here I have corrected Lit ids 
https://github.com/BetaMasaheft/Documentation/issues/2707

2025-01-02 08:56 UTC, MassimoVilla approved these changes
Thank you Nafisa, I only have one comment about one sentence

2025-01-02 08:56 UTC, MassimoVilla commented on 3001-4000/LIT3200DossierEw.xml
> +            <ab>The collection consisiting Life (in one of several redactions), Miracles (varying
There's something in the wording to be revised here

2025-01-06 09:58 UTC, thea-m requested changes
Thank you, extremely helpful!

2025-01-06 09:58 UTC, thea-m commented on 3001-4000/LIT3200DossierEw.xml
> +            <ab>The collection consisits of the Life (in one of several redactions), Miracles (in a varying
in the general record, "recension" has been used. I think it would be good to use the same term in all records.

2025-01-06 09:58 UTC, thea-m commented on 4001-5000/LIT4320GadlaEB.xml
> +               is believed to represent an elaborated shorter version of the 'redaction α', as
I think it would be useful to link here to the work records of redaction a

2025-01-06 09:58 UTC, thea-m commented on 4001-5000/LIT4321GadlaEC.xml
> +               is believed to represent an elaborated shorter version of the 'redaction β', as
also link to work record

2025-01-06 10:16 UTC, thea-m approved these changes

2025-01-06 11:45 UTC, merged