Update LIT2393tabiba.xml
BetaMasaheft/Works pull request #306
Opened 2020-09-29 14:43 UTC by DenisNosnitsin1970

update

2020-09-30 08:40 UTC, smaugustine commented
Just to note, the former IDs are LIT3084RepCh364 and LIT3092RepCh372 (the first numeric parts are missing in the commit).

2020-09-30 08:58 UTC, DenisNosnitsin1970 commented
Indeed. Thanks!

2020-09-30 09:46 UTC, thea-m commented
Thank you! Will you make a new PR to delete the other records? Have references to the old IDs the manuscripts been updated?

2020-09-30 09:54 UTC, DenisNosnitsin1970 commented
Not yet, I will do that.

2020-09-30 10:24 UTC, thea-m commented
Then I will merge this when the manuscript PR is done, otherwise we will have chaos

2020-10-01 13:20 UTC, eu-genia requested changes

2020-10-01 13:20 UTC, eu-genia commented on 2001-3000/LIT2393tabiba.xml
>        </body>
The bibliography from the deleted records is missing and must be provided here
```
<listBibl type="editions">
               <bibl>
                  <ptr target="bm:Chaine1913Rep"/>
                  <citedRange unit="item">364</citedRange>
               </bibl>
 <bibl>
                  <ptr target="bm:Chaine1913Rep"/>
                  <citedRange unit="item">372</citedRange>
               </bibl>
</listBibl>
```

2020-10-01 13:20 UTC, eu-genia commented
Just to link this to the related PR in MSS: https://github.com/BetaMasaheft/Manuscripts/pull/796

2020-10-01 13:46 UTC, eu-genia requested changes

2020-10-01 13:46 UTC, eu-genia commented on 2001-3000/LIT2393tabiba.xml
> +            <div type="bibliography">
there is something wrong with the nesting, you already had the `<div type="bibliography">` opened in line 48 above, please remove line 59

2020-10-01 13:55 UTC, eu-genia approved these changes

2020-10-01 13:55 UTC, merged