Lit6203 malkea seqlat
BetaMasaheft/Works pull request #331
Opened 2020-10-19 16:35 UTC by MarcinKrawczuk

This is a malk poem from EMML 1939.

2020-10-20 10:28 UTC, DariaElagina commented on new/LIT6203MalkeaSeqlat.xml
> +            <div type="textpart" subtype="incipit">
you could add xml:lanf either to ab or to div

2020-10-27 08:28 UTC, thea-m requested changes
Thank you, two minor remarks

2020-10-27 08:28 UTC, thea-m commented on new/LIT6203MalkeaSeqlat.xml
> +                <title xml:lang="gez" corresp="*t1">Malkǝʾa Sǝqlat</title>
sǝqlat with a small s. Normally, only the first word of work titles is spelled with a capital, except for proper names

2020-10-27 08:28 UTC, thea-m commented on new/LIT6203MalkeaSeqlat.xml
> +          <div xml:lang="gez" type="edition">
It is always better to indicate explicitly in the record from which source the text has been taken. You can write simply a `<note>` in edition with something like "This text is taken from MS xy"

2020-10-28 07:57 UTC, thea-m approved these changes

2020-10-30 08:22 UTC, merged