Miracles of george (4)
BetaMasaheft/Works pull request #351
Opened 2020-11-06 19:22 UTC by SusanneHummel

Here are four more new miracles contained in BDLaethb4. Unfortunately, another six are in a separate PR

For the former issue on creating those files: BetaMasaheft/Documentation#1491

Concering the titles:
The first title is our own, the second and third titles are taken from the catalogues by Strelcyn and Grebaut/Tisserant.

2020-11-07 12:40 UTC, Gnisci commented on new/LIT6218MGMoney.xml
> +                    denied to pay back the money from the priest</title>
refused to pay back to a priest

2020-11-09 08:23 UTC, MassimoVilla requested changes
Thank you!!

2020-11-09 08:23 UTC, MassimoVilla commented on new/LIT6218MGMoney.xml
> +                            ምስለ፡<gap reason="ellipsis" resp="SH"/>
I would leave a space between  ምስለ፡ and `<gap reason="ellipsis" resp="SH"/>`

2020-11-10 17:23 UTC, SusanneHummel commented
Thank you! I updated the file.

2020-11-10 17:40 UTC, MassimoVilla approved these changes

2020-11-16 13:22 UTC, thea-m requested changes
Thank you!

2020-11-16 13:22 UTC, thea-m commented on new/LIT6218MGMoney.xml
> +                            ወዐበይት፡ እምኵለሄ። ወአምጽኡ፡ ንዋየ፡ ብዙኃ፡ ወመሳቀለ፡ ዘወርቅ፡ ወብሩር፡ ወአጽሕልተ፡
መሳቅለ?

2020-11-16 15:38 UTC, SusanneHummel commented on new/LIT6218MGMoney.xml
> +                            ወዐበይት፡ እምኵለሄ። ወአምጽኡ፡ ንዋየ፡ ብዙኃ፡ ወመሳቀለ፡ ዘወርቅ፡ ወብሩር፡ ወአጽሕልተ፡
መሳቀለ
I changed it

2020-11-16 17:10 UTC, thea-m approved these changes

2020-11-16 17:10 UTC, merged