SH-MG-3: Three more miracles of George
BetaMasaheft/Works pull request #367
Opened 2020-11-16 18:31 UTC by SusanneHummel

Here come three more miracles, all in all now 22 out of 42

slowly but surely ...

or as we say in German "mühsam ernährt sich das Eichhörnchen"

2020-11-16 20:22 UTC, Gnisci requested changes

2020-11-16 20:22 UTC, Gnisci commented on new/LIT6234MGBebaPalm.xml
> +                <title xml:id="t2" xml:lang="en">How a man hated the saint was killed</title>
man "who" hated the saint

2020-11-16 20:22 UTC, Gnisci commented on new/LIT6236MGEucharist.xml
> +                    Eucharist and dies a suffering death</title>
an agonizing/painful death

2020-11-17 09:09 UTC, MassimoVilla requested changes
Thank you Sanne!

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6235MGOldCairo.xml
> +                        <citedRange unit="page">9–10 (21th miracle)</citedRange>
21st miracle

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6235MGOldCairo.xml
> +                        <citedRange unit="page">15–18 (21th miracle)</citedRange>
21st miracle

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6235MGOldCairo.xml
> +                        <citedRange unit="item">Ms 12, II.22 (21th miracle)</citedRange>
21st

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6235MGOldCairo.xml
> +                        <citedRange unit="item">Vat 233, 3.22 (21th miracle)</citedRange>
21st

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6236MGEucharist.xml
> +                        <citedRange unit="page">18–20 (22th miracle)</citedRange>
22nd

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6236MGEucharist.xml
> +                        <citedRange unit="page">10–11 (22th miracle)</citedRange>
22nd

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6236MGEucharist.xml
> +                        <citedRange unit="item">Ms 12, II.23 (22th miracle)</citedRange>
22nd

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6236MGEucharist.xml
> +                        <citedRange unit="item">Vat 233, 3.23 (22th miracle)</citedRange>
22nd

2020-11-17 09:09 UTC, MassimoVilla commented on new/LIT6236MGEucharist.xml
> +                            ለእግዚአብሔር፡ ስቡሕ፡ ወልዑል። ወለቅዱስ፡ ማር፡ ጊዮርጊrb ስ፡ ጸሎቱ፡ ወበረከቱ፡ የሀሉ፡ ምስለ፡ <gap
ጊዮርጊስ፡ ?

2020-11-17 09:14 UTC, thea-m requested changes
Thank you!

2020-11-17 09:14 UTC, thea-m commented on new/LIT6235MGOldCairo.xml
> +                            ወልዑል፡ ገባሬ፡ ተአምራት፡ በደ፡ ሰማዕት፡ ቅዱስ፡ ጊዮርጊስ፡ ጸሎቱ፡ ወበረከቱ፡ የሀሉ፡ ምስለ፡ <gap
በደ in the ms?

2020-11-17 09:14 UTC, thea-m commented on new/LIT6236MGEucharist.xml
> +                <title xml:lang="gez" xml:id="t1">Miracle of St George: A pagan woman takes the
en

2020-11-17 09:15 UTC, thea-m commented
More than half of them done now!!

2020-11-20 09:57 UTC, SusanneHummel reviewed
Thank to all! I incorpoartted all your ssuggestions.

2020-11-20 09:57 UTC, SusanneHummel commented on new/LIT6235MGOldCairo.xml
> +                            ወልዑል፡ ገባሬ፡ ተአምራት፡ በደ፡ ሰማዕት፡ ቅዱስ፡ ጊዮርጊስ፡ ጸሎቱ፡ ወበረከቱ፡ የሀሉ፡ ምስለ፡ <gap
በእደ፡

2020-11-20 14:59 UTC, MassimoVilla approved these changes

2020-11-20 16:38 UTC, thea-m approved these changes

2020-11-20 16:39 UTC, merged