Create LIT6465PaterNostCoptBoh.xml
BetaMasaheft/Works pull request #564
Opened 2021-06-18 16:52 UTC by DenisNosnitsin1970

New entry.  How can it be linked to ETH1292Bohair? Shoult they be linked?

2021-06-18 19:09 UTC, eu-genia commented
do we create a work record for each language version? I thought our rule was one work one record, languages are distinguished by title ids

2021-06-21 10:16 UTC, thea-m commented
I would also tend towards sticking with the existing ID LIT2168PaterN. If you agree with us, this PR has to be merged and a new PR created for the deletion of the new ID. Otherwise, I think this discussion should better be transferred to an issue.

2021-06-21 10:19 UTC, eu-genia commented
yes, cp. also my comment here https://github.com/BetaMasaheft/Manuscripts/pull/1149#discussion_r654632874

2021-06-21 11:26 UTC, eu-genia requested changes

2021-06-21 11:26 UTC, eu-genia commented on 2001-3000/LIT2168PaterN.xml
>              <title xml:id="t2">Lord’s Prayer, Our Father</title>
lord's prayer and our father are two separate titles
I suggest
```
<title xml:id="t1" xml:lang="lat">Pater Noster</title>
<title corresp="#t1" xml:lang="en">Our Father</title>
<title xml:id="t2" xml:lang="en">Lord's Prayer</title>
```

2021-06-21 11:26 UTC, eu-genia commented on 2001-3000/LIT2168PaterN.xml
> +              <title xml:lang="gez" corresp="#t3" type="normalized">ʾAbuna zabasamāyāt</title>
I would supply language to title IDs, t3geez and add translation

`<title corresp="#t3" xml:lang="en">Our Father in Heaven</title>
`

2021-06-21 12:00 UTC, eu-genia approved these changes

2021-06-21 12:00 UTC, merged

2021-06-22 17:23 UTC, thea-m commented
I think that the correct workflow in such cases is to create the superfluous record and then make a new PR for the deletion...