LIT6470 71 72 80 81
BetaMasaheft/Works pull request #578
Opened 2021-07-08 09:59 UTC by DenisNosnitsin1970

New entries. One Malke'a Mamas is too much, I will delete it in a different PR. A correction in the record for Agerhese Abana Mamas is necessary, I will do it.

2021-07-12 09:56 UTC, thea-m requested changes
Thank you! Just for the future, could you please provide in the initial comment of the PR the link to the issue where these works were discussed?

2021-07-12 10:04 UTC, DenisNosnitsin1970 commented on new/LIT6481DossierMamas.xml
> +                <title xml:lang="gez" xml:id="t1">Hagiographic Dossier of Māmās</title>
ok, i will do

2021-08-02 10:09 UTC, eu-genia requested changes

2021-08-02 10:09 UTC, eu-genia commented on new/LIT6480MalkeaMamas.xml
> +                <title xml:lang="gez" xml:id="t1">MalkeaMamas</title>
transcription to correct

2021-08-02 10:20 UTC, eu-genia commented
Just to link here: https://github.com/BetaMasaheft/Documentation/issues/1773

2021-08-19 12:00 UTC, eu-genia commented
still corrections to do? 
by the way LIT4775GadlaMa is about still another Mamas (PRS6626Mammas)? 
(I guess we also have to harmonize Mamas/Mammas)

2021-08-20 07:26 UTC, eu-genia commented
so PRS6626Mammas is the same as PRS13452Mamas?
and LIT4775GadlaMa is the same as LIT6470GadlaMamas (not yet merged)?

2021-08-20 08:00 UTC, DenisNosnitsin1970 commented
Yes. "Gadla Māmmās za-Gʷǝgʷǝdā" LIT4775GadlaMa is the same.

2021-08-20 08:12 UTC, eu-genia commented
So I suggest that the information from LIT4775GadlaMa is moved to LIT6470GadlaMamas (title, KRZ) and 4775 can be deleted (wuth a relation formerlyListedAs)
Also PRS6626Mammas and PRS13452Mamas should be merged

2021-08-20 08:14 UTC, DenisNosnitsin1970 commented
OK.

2021-08-24 08:56 UTC, eu-genia approved these changes

2021-08-24 13:14 UTC, eu-genia approved these changes

2021-08-24 13:14 UTC, thea-m approved these changes

2021-08-24 13:15 UTC, merged

2021-08-24 13:15 UTC, thea-m commented
Now the deletion of LIT6480MalkeaMamas remains for a new PR

2021-08-24 13:16 UTC, DenisNosnitsin1970 commented
indeed.