Update LIT1639Homily.xml
BetaMasaheft/Works pull request #587
Opened 2021-07-21 21:07 UTC by MarcinKrawczuk

Added two clavis numbers, sth I haven't done before so I hope it's correct. I checked two mss. and the attribution of the translation to Salama is in both at the end.

2021-07-22 08:18 UTC, DariaElagina requested changes

2021-07-22 08:18 UTC, DariaElagina commented on 1001-2000/LIT1639Homily.xml
> +                   <ptr target="bm:CANT"/>
bibl type="CANT" cp. with another bibl

2021-07-22 17:55 UTC, MarcinKrawczuk commented on 1001-2000/LIT1639Homily.xml
> +                   <ptr target="bm:CANT"/>
Done

2021-07-23 10:33 UTC, DariaElagina approved these changes

2021-07-23 10:33 UTC, merged