Lit1618 homily corr mk
BetaMasaheft/Works pull request #616
Opened 2021-09-13 19:49 UTC by MarcinKrawczuk

2021-09-14 11:30 UTC, thea-m requested changes

2021-09-14 11:30 UTC, thea-m commented on 1001-2000/LIT1618Homily.xml
> +           <title xml:lang="gez" type="normalized" corresp="#t1">Dǝrsān za-ʾabbā Yāʿqob za-śāls sanbata krǝstiyān za-yǝtnabbab za-ṣom</title>
I would be in favour of śālǝs

2021-09-14 15:25 UTC, MarcinKrawczuk commented on 1001-2000/LIT1618Homily.xml
> +           <title xml:lang="gez" type="normalized" corresp="#t1">Dǝrsān za-ʾabbā Yāʿqob za-śāls sanbata krǝstiyān za-yǝtnabbab za-ṣom</title>
Done

2021-09-15 10:38 UTC, thea-m approved these changes

2021-09-15 10:38 UTC, merged