LIT2382 6396
BetaMasaheft/Works pull request #636
Opened 2021-11-03 11:14 UTC by DenisNosnitsin1970

An update for the Miracles of Jesus and the Introduction.

2021-11-03 11:48 UTC, thea-m requested changes

2021-11-03 11:48 UTC, thea-m commented on 2001-3000/LIT2382Taamme.xml
> +               <label>Introduction, Grébaut 1917 No. 1 (1-6)</label>
Could you mark up the reference, here and later?

2021-11-04 12:55 UTC, DenisNosnitsin1970 commented
I will add number of pages ot miracles 31-40 as soon as I reach the publication.

2022-04-14 11:12 UTC, thea-m commented
@DenisNosnitsin1970 just so that we don't forget it. If you have the opportunity, could you add the links?

2022-04-14 11:16 UTC, DenisNosnitsin1970 commented
Yes.

2022-04-21 19:45 UTC, DenisNosnitsin1970 commented
Sorry, at this point I have to ask, which links are meant?

2022-04-22 09:17 UTC, thea-m commented
I'm sorry, I meant the page numbers of the miracles 31-40. No idea what made me write links.

2022-04-22 09:36 UTC, eu-genia approved these changes

2022-04-22 09:43 UTC, eu-genia commented
the pages are added but there is something wrong with this branch, I will remove 6396 from here and commit it separately

2022-04-22 09:43 UTC, merged

2022-04-22 12:21 UTC, thea-m commented
I still don't see the page numbers for miracles 31-40

2022-04-22 12:26 UTC, DenisNosnitsin1970 commented
I think they are not published, if I am not mistaken.

2022-04-22 12:47 UTC, eu-genia commented
Yes I have merged all

2022-04-22 12:48 UTC, eu-genia commented
You mean page numbers? sorry I thought they were, if there is more to edit please create a new branch/PR

2022-04-22 12:48 UTC, eu-genia commented
The current version has numbers up to number 30

2022-04-22 13:58 UTC, DenisNosnitsin1970 commented
I added for those which are edited. For the rest only numbers from the article.