Works in bd laethg31
BetaMasaheft/Works pull request #712
Opened 2022-03-01 14:11 UTC by MassimoVilla

Here come two new work records based on MS BDLaethg31

2022-03-02 09:54 UTC, thea-m requested changes

2022-03-02 09:54 UTC, thea-m commented on new/LIT6572Ardaihu.xml
> +                        ወአንተሂ፡ ዘንተ፡ ጸሎተ፡ ለአመ፡ ተአመንከ፡ ኵሉ፡ ይትገበር፡ ለከ፡ በዝንቱ፡ ጸሎት። ወማየ፡ ጸሎትይሂ፡ ኢይትከዓው፡ ውስተ፡ ምድር። እስመ፡ ክቡር፡ ወቅዱስ፡
ጸሎትይሂ in the ms?

2022-03-02 11:53 UTC, MassimoVilla commented on new/LIT6572Ardaihu.xml
> +                        ወአንተሂ፡ ዘንተ፡ ጸሎተ፡ ለአመ፡ ተአመንከ፡ ኵሉ፡ ይትገበር፡ ለከ፡ በዝንቱ፡ ጸሎት። ወማየ፡ ጸሎትይሂ፡ ኢይትከዓው፡ ውስተ፡ ምድር። እስመ፡ ክቡር፡ ወቅዱስ፡
You are right! It's simply ጸሎትሂ

2022-03-07 12:02 UTC, thea-m approved these changes

2022-03-07 12:02 UTC, merged