LIT 6576 6577
BetaMasaheft/Works pull request #737
Opened 2022-03-15 17:51 UTC by DenisNosnitsin1970

Records for Dossier and Miracles of Mabaa Seyon. I constructed the miracles from a few sources, as only a part was edited by Budge. The list can be revised and corrected when more mss will be processed.

2022-03-16 10:13 UTC, eu-genia approved these changes

2022-03-16 11:00 UTC, thea-m requested changes

2022-03-16 11:00 UTC, thea-m commented on new/LIT6576MiraclesMabaSeyon.xml
> +                     በስመ፡ አብ፡<gap reason="omitted"/> ንጽሕፍ፡ እንከ፡ ድርሳነ፡ ተዝካረ፡ መድኃኒነ፡
I think what is meant here and below is gap reason="ellipsis"?

2022-03-16 11:52 UTC, eu-genia commented
Denis, I am sorry, your last commit overwrites the corrections by me and Dorothea, because you did not refresh your branch with the commits we have pushed. Please take over the corrections we already did. 
In future, please always fetch and pull before committing any changes.
Thank you.

2022-03-16 11:54 UTC, eu-genia commented
Take this file (the last pushed by Dorothea) https://raw.githubusercontent.com/BetaMasaheft/Works/9622d668f39d2f729d94acb48026849b9a7f046f/new/LIT6576MiraclesMabaSeyon.xml
and work with this one.

2022-03-16 15:48 UTC, DenisNosnitsin1970 commented
Which corrections? If you know that I am dealing with that and there is one open request, you do not need to intervene. The only correction I introduce was to substitute "omitted" for "ellipsis"

2022-03-16 16:35 UTC, thea-m commented
This: https://github.com/BetaMasaheft/Works/pull/737/commits/9622d668f39d2f729d94acb48026849b9a7f046f
It is only the transcription of Taʾammərātihu, you can just repeat it in your version of the file.

2022-03-16 16:36 UTC, thea-m commented
If you prefer, I can stop carrying out corrections of obvious typos in PRs. I just personally find it a waste of time for one person to state the presence of a type and then a second person to go and correct it, when the first person could do it in the same time as writing the comment.

2022-03-16 23:30 UTC, eu-genia commented
Please check my commits before Dorothea's. I sent you a link to the latest version of the file which had my many corrections and hers.
(bm:bm-->bm:, emml->EMML, etc.)

2022-03-16 23:33 UTC, eu-genia approved these changes

2022-03-16 23:33 UTC, eu-genia commented
I have now reintroduced the corrections

2022-03-17 09:03 UTC, merged

2022-03-17 09:10 UTC, DenisNosnitsin1970 commented
The corrections are in fact three or four, just recurrent. 
The record is not displayed in the BM.

2022-03-17 09:11 UTC, DenisNosnitsin1970 commented
It is displayed, but somehow wrong, without the content.

2022-03-17 09:15 UTC, eu-genia commented
now is ok; i think the app was offline (i was editing the navigation) when you did the push so the webhook did not work

2022-03-17 09:17 UTC, DenisNosnitsin1970 commented
I still have a few corrections, I will creat a new branch, as usual.