LIT 3143 3972 4336
BetaMasaheft/Works pull request #752
Opened 2022-03-21 13:57 UTC by DenisNosnitsin1970

I tried to complete and disambiguate the genealogies related to Takla Hazmanot.

2022-03-21 14:46 UTC, thea-m requested changes
Thank you! Everything that is there seems fine to me, and is very helpful. But I would be grateful if you could include an abstract in each record which very briefly describes the work in question and , if relevant, its relation/disambiguation from the other works. I think that this is one of the cases where paragraphic information is appropriate.

2022-03-21 16:22 UTC, DenisNosnitsin1970 commented
I have tried.

2022-03-22 08:59 UTC, thea-m commented
Here, in this PR? I don't see an abstract in the records.

2022-03-22 09:31 UTC, DenisNosnitsin1970 commented
Now. No idea why it got stuck in the pipe.

2022-03-22 09:32 UTC, thea-m requested changes
Thank you! One minor question.

2022-03-22 09:32 UTC, thea-m commented on 3001-4000/LIT3143Ledata.xml
> +             his spiritual descendance from <persName ref="PRS1385Adam">St Anthony</persName> and tells about his disciples
Adam or Anthony?

2022-03-22 09:35 UTC, DenisNosnitsin1970 commented on 3001-4000/LIT3143Ledata.xml
> +             his spiritual descendance from <persName ref="PRS1385Adam">St Anthony</persName> and tells about his disciples
Anthony.

2022-03-22 09:41 UTC, thea-m approved these changes

2022-03-22 09:41 UTC, merged