Create LIT6606JohnAlms.xml
BetaMasaheft/Works pull request #778
Opened 2022-03-28 16:43 UTC by MarcinKrawczuk

https://github.com/BetaMasaheft/Documentation/issues/2018

2022-04-11 11:53 UTC, thea-m approved these changes

2022-04-11 12:00 UTC, thea-m requested changes
Actually, now I noticed some ID confusion with this record and LIT6607JohnFast - the IDs and the titles seem to be interchanged? 
In theory, the alphabetical part of the IDs is irrelevant, but since we cannot help but read it and also use it for orientation, maybe you could fix this? I think the easiest would be - if my interpretation is right - to copy paste and exchange the complete content of both records. This would allow to keep the IDs. If you prefer to change the IDs, it would be necessary to merge the two pull requests and then make a new one for the deletion of the files, and again a new one for the creation of the new records.
I hope you understand what I mean :) My writing seems a bit confused to myself.

2022-09-12 07:06 UTC, thea-m approved these changes

2022-09-12 07:07 UTC, merged

2022-10-11 09:03 UTC, MarcinKrawczuk commented
Thank you very much for pointing that out. However I won't be able to work
on it this week, because I'm going away for the Easter period. But I will
fix it as soon as possible.



pon., 11 kwi 2022 o 14:00 thea-m ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Actually, now I noticed some ID confusion with this record and
> LIT6607JohnFast - the IDs and the titles seem to be interchanged?
> In theory, the alphabetical part of the IDs is irrelevant, but since we
> cannot help but read it and also use it for orientation, maybe you could
> fix this? I think the easiest would be - if my interpretation is right - to
> copy paste and exchange the complete content of both records. This would
> allow to keep the IDs. If you prefer to change the IDs, it would be
> necessary to merge the two pull requests and then make a new one for the
> deletion of the files, and again a new one for the creation of the new
> records.
> I hope you understand what I mean :) My writing seems a bit confused to
> myself.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/778#pullrequestreview-937889099>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJQ4BHR74BMGNFL2YUTVEQH5PANCNFSM5R3XOQ2A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>