Update LIT6193HomiliaryPassions.xml
BetaMasaheft/Works pull request #786
Opened 2022-04-20 16:39 UTC by DenisNosnitsin1970

An update

2022-04-20 17:33 UTC, eu-genia requested changes

2022-04-20 17:33 UTC, eu-genia commented on 6001-7000/LIT6193HomiliaryPassions.xml
> +                  <ptr target="bm:bm:Segesellase1996DersanaMedhane"/>
one bm: only

2022-04-20 18:31 UTC, DenisNosnitsin1970 commented on 6001-7000/LIT6193HomiliaryPassions.xml
> +                  <ptr target="bm:bm:Segesellase1996DersanaMedhane"/>
Done.

2022-04-20 18:46 UTC, eu-genia approved these changes

2022-04-20 18:46 UTC, merged

2022-05-25 09:36 UTC, eu-genia commented
https://github.com/BetaMasaheft/Documentation/issues/1500
https://github.com/BetaMasaheft/Documentation/issues/2077