Update LIT6208CyriacusPilate.xml
BetaMasaheft/Works pull request #816
Opened 2022-05-09 20:58 UTC by MarcinKrawczuk

2022-05-10 02:16 UTC, eu-genia requested changes

2022-05-10 02:16 UTC, eu-genia commented on 6001-7000/LIT6208CyriacusPilate.xml
> +<listBibl type="secondary">
type="clavis"?

2022-05-10 20:22 UTC, MarcinKrawczuk commented
OK done

wt., 10 maj 2022 o 04:17 Eugenia ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In 6001-7000/LIT6208CyriacusPilate.xml
> <https://github.com/BetaMasaheft/Works/pull/816#discussion_r868751102>:
>
> > @@ -61,6 +68,19 @@ type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
>                      <relation name="ecrm:CLP46i_may_form_part_of" active="LIT6208CyriacusPilate" passive="LIT1493Gadlas"/>
>                      <relation name="saws:isAttributedToAuthor" active="LIT6208CyriacusPilate" passive="PRS3251Cyriacus"/>
>                  </listRelation>
> +
> +                <listBibl type="editions">
> +                  <bibl><ptr target="bm:Oudenrijn1959Gamaliel"/><citedRange unit="page">112-168</citedRange></bibl>
> +                </listBibl>
> +
> +<listBibl type="secondary">
>
> type="clavis"?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/816#pullrequestreview-967088564>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJQBLDHSVLUENZOLIBDVJHBJZANCNFSM5VPPBQLQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-11 07:49 UTC, eu-genia approved these changes

2022-05-11 07:49 UTC, merged