Lit6620 der hom kah
BetaMasaheft/Works pull request #817
Opened 2022-05-09 21:19 UTC by MarcinKrawczuk

2022-05-10 02:13 UTC, eu-genia requested changes

2022-05-10 02:13 UTC, eu-genia commented on new/LIT6620DerHomKah.xml
> +                      <div type="bibliography"/>
please remove the `div type="bibliography" `around the `div type="edition"`. thank you

2022-05-10 02:13 UTC, eu-genia commented on new/LIT6620DerHomKah.xml
> +                <editor role="generalEditor" key="AB"/>
maybe add as a title variant "... heavenly priests" as they are often referred to that way

2022-05-10 20:20 UTC, MarcinKrawczuk commented
Done (I hope)

wt., 10 maj 2022 o 04:13 Eugenia ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In new/LIT6620DerHomKah.xml
> <https://github.com/BetaMasaheft/Works/pull/817#discussion_r868749060>:
>
> > +            <change who="MKr" when="2022-04-27">Created entity</change>
>
> +        </revisionDesc>
>
> +    </teiHeader>
>
> +    <text>
>
> +        <body>
>
> +            <div type="bibliography">
>
> +                <listRelation>
>
> +                    <relation name="saws:isDifferentTo" active="LIT6620DerHomKah" passive="LIT6614FourCreat"/>
>
> +                    <relation name="saws:isDifferentTo" active="LIT6620DerHomKah" passive="LIT4958Priests"/>
>
> +                    <relation name="saws:isDifferentTo" active="LIT6620DerHomKah" passive="LIT6469HomilyKahenat"/>
>
> +                    <relation name="ecrm:P129_is_about" active="LIT6620DerHomKah" passive="PRS12519TwentyFour"/>
>
> +                </listRelation>
>
> +            </div><!---->
>
> +
>
> +
>
> +                      <div type="bibliography"/>
>
>
> please remove the div type="bibliography" around the div type="edition".
> thank you
> ------------------------------
>
> In new/LIT6620DerHomKah.xml
> <https://github.com/BetaMasaheft/Works/pull/817#discussion_r868750575>:
>
> > @@ -0,0 +1,77 @@
>
> +<?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
>
> +schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="https://raw.githubusercontent.com/BetaMasaheft/schema/master/tei-betamesaheft.rng"
>
> +type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
>
> +<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="LIT6620DerHomKah" xml:lang="en" type="work">
>
> +    <teiHeader>
>
> +        <fileDesc>
>
> +            <titleStmt>
>
> +                <title xml:lang="gez" xml:id="t1">ድርሳን፡ ዘ፳ወ፬፡ ካህናተ፡ ሰማይ፡</title>
>
> +                <title xml:lang="gez" type="normalized" corresp="#t1">Dǝrsān za20wa4 kāhǝnāta samāy</title>
>
> +                <title xml:lang="en" xml:id="t2">Homily for the commemoration of the Twenty-Four Elders of Heaven</title>
>
> +                <editor role="generalEditor" key="AB"/>
>
>
> maybe add as a title variant "... heavenly priests" as they are often
> referred to that way
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BetaMasaheft/Works/pull/817#pullrequestreview-967086836>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO62KJRKKZIYD56IDG6VYFLVJHA4PANCNFSM5VPQVX3A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-11 07:52 UTC, eu-genia approved these changes

2022-05-11 07:53 UTC, eu-genia commented
> Done (I hope) 
I corrected the nesting, you deleted too much and in the end still had the edition inside of bibliography ;)

2022-05-11 07:53 UTC, merged