new records
BetaMasaheft/Works pull request #855
Opened 2022-08-09 14:18 UTC by thea-m

https://github.com/BetaMasaheft/Documentation/issues/2182
https://github.com/BetaMasaheft/Documentation/issues/2181

2022-08-10 09:30 UTC, MassimoVilla requested changes
Thank you Thea, I just have two minor observations due to the very mediocre handwriting of the additions

2022-08-10 09:30 UTC, MassimoVilla commented on new/LIT6702MashafaKobor.xml
> +                        ሰገም፡ ይሰምር፡ ሰናይ፡ ይሰምር፡ ሕፃናተ፡ ይሙውቱ ፨</ab>
The handwriting is not very clear, but I read the nominative form ሕፃናት (which agrees with the following verb ይመውቱ፡). The vowel marker of ት is just hinted.

2022-08-10 09:30 UTC, MassimoVilla commented on new/LIT6703HymnMik.xml
> +                        ሰላም፡ ለአስተረዕዮትከ፡ ውስተ፡ ደብረ፤ ማህው፡ ዘዮም፡ ዘምስለ፡ <sic>ቅብ</sic>
I think it is ለአስተርዕዮትከ፡
Also, in the MS I see `<sic>ወስተ</sic>`, as indicated in https://github.com/BetaMasaheft/Documentation/issues/2182

2022-08-10 10:02 UTC, thea-m commented
Thanks a lot, Massimo!

2022-09-01 10:44 UTC, thea-m commented
Can this be merged?

2022-09-01 15:51 UTC, MassimoVilla approved these changes

2022-09-01 15:52 UTC, merged

2022-09-02 11:00 UTC, karljonaskarlsson commented on new/LIT6702MashafaKobor.xml
> +                    <ab>ለእመ፡ በእሑድ፡ ሐማም፡ ይበዝኅ፡ እክል፡ ወነግድ፡ ይሠምር፡ ፄው፡ ፀሐፅፅ፡ አልባሰ፡ ሐርስ፡ ዝናም፡
"የሐፅፅ"?