Miracles in ms e.39
BetaMasaheft/Works pull request #912
Opened 2022-10-25 12:34 UTC by MassimoVilla

Here comes the set of miracles included in MS e.39 plus one not included in this MS but published and translated by Paolo Marrassini in his _"Vita", "Omelia", "Miracoli" del santo Gabra Manfas Qeddus_, so that all edited miracles are now included in the BM database.

2022-10-25 14:31 UTC, thea-m requested changes
Thank you, that's really wonderful!

2022-10-25 14:31 UTC, thea-m commented on new/LIT6778MiracleGMQ.xml
> +                        ወጸልመ፡ ፀሐይ፡ ወወርኅ፡ ወከዋክት፡ ሰማይ፡ ወምድር፡ ርዕደት፡ ወአድለቅለቁ፡ መቃብራት፡ ወነጐድጓድ፡ በይእቲ፡ ዕለት፡
ከዋክብት?

2022-10-25 18:58 UTC, MarcinKrawczuk commented on new/LIT6765MiracleGMQ.xml
> +                        አቡነ፡ ገብረ፡ መንፈስ፡ ቅዱስ፡ ወእምድረዝ፡ ዓርገ፡ ሰማያት፡ ነፍሱ፡ ወሥጋሁ፡
ወእምድኅረዝ፡ ?

2022-10-25 19:03 UTC, MarcinKrawczuk commented on new/LIT6772MiracleGMQ.xml
> +                        ተአምሪሁ፡ ለአቡነ፡ገብረ፡ መንፈስ፡ ቅዱስ፡ ጸሎቱ፡ ወበረከቱ፡
Add space

2022-10-25 19:06 UTC, MarcinKrawczuk approved these changes

2022-10-26 12:33 UTC, MassimoVilla commented on new/LIT6769MiracleGMQ.xml
> +                        ከመ፡ ፀንሰት፡ ወለከ፡ ኀበ፡ መምህራ። መምህራሰ፡ መዓትም፡ ውእቱ፡ ወሶበ፡ ሰምዓ፡ ዘንተ፡ ነገረ፡ ለአከ፡ እንዘ፡ ይብል፡ በሣልስት፡
you are right, one letter between ወ and ለ is no more legible. 
I corrected the word into `ወ<gap reason="illegible" unit="chars" quantity="1"/>ለከ፡`

2022-10-26 12:56 UTC, MassimoVilla commented
All corrections have been incorporated and the explicits added. Thank you!

2022-10-28 15:46 UTC, MassimoVilla commented
Merging is still blocked, one more approval is still needed after the suggested changes have been made

2022-11-07 11:51 UTC, thea-m approved these changes
Thank you, sorry for keeping you so long

2022-11-07 11:51 UTC, merged