Didascalia of the 318 nicene fathers
BetaMasaheft/Works pull request #975
Opened 2023-05-03 12:42 UTC by MarcinKrawczuk

Let me remind:
LIT2432Teachi - general record
LIT1313Discou - "old" version
LIT6819Teachi318A - "new" version --> I will create it in a separate branch

Once all the three are done, I will clean the situation in manuscripts.

2023-05-03 14:25 UTC, CarstenHoffmannMarburg approved these changes

2023-05-04 07:40 UTC, thea-m requested changes
Thank you, that is really great and useful

2023-05-04 07:40 UTC, thea-m commented on 1001-2000/LIT1313Discou.xml
> +b) the younger one, certainly translated from Arabic and transmitted as part of Haymānota ʾabaw.</p>
if we know for sure the ID for the younger one will be LIT6819Teachi318A , I would refer already here to it (The younger one, `<ref type="work" corresp="LIT6819Teachi318A"/>`, ....)

2023-05-08 10:44 UTC, thea-m approved these changes

2023-05-08 10:44 UTC, thea-m approved these changes

2023-05-08 10:44 UTC, merged