homily on nativity updates
BetaMasaheft/Works pull request #991
Opened 2023-05-24 11:03 UTC by thea-m

https://github.com/BetaMasaheft/Documentation/issues/2358

I have:

- Updated the references in the record of the Hāymānota ʾabaw
- added bibliography to LIT6605JacobNat and LIT6711JacSarGena
- deleted LIT1186Baenta, which had been created from the EAe index and referred to the attestation in the Hāymānota ʾabaw

Please let me know if I missed anything or you would like to add something else.
(Related: I have no copy of bm:Bedjan1902Cantus, so the corresponding zotero entry based on bibliographic references found elsewhere is probably inadequate)

Thank you!

2023-05-24 16:21 UTC, MarcinKrawczuk approved these changes

2023-05-30 14:37 UTC, AaronButts commented
Thanks, Dorothea, for this, and sorry for the delay in my response: Time has been short. 

I still have some difficulty reading the code, but I think that there are problems with the bibliography, at least with the identifier B2. This refers to a clavis-type list of homilies of Jacob published by Brock. 

More broadly, I wonder about including the A = B1 = B2 identifiers at this stage. This is a main part of the work that Ted and I are doing, and it probably makes sense to incorporate such identifiers all together, for all of Jacob's homilies, once our work is done. That is, I don't like the lack of symmetry in having such specific identifiers for one homily attributed to Jacob but not the many others. Ted and I plan to provide this info to Bm at some point for all the homilies. Waiting a bit also allows us all to sort out the credit for these identifications. That is, identifying these individual homilies by Jacob is a major part of a book that Ted and I will publish relatively soon (plan to submit it this year), and it undercuts our work to have the identifications already in Bm (especially without credit). These are of course issues that can be sorted out in due course. 

All that to say, I would suggest not providing the Syriac identifications at least for now. 

What do you think?

2024-09-23 10:33 UTC, eu-genia commented
@thea-m can you resolve conflicts and merge when you can?

2025-01-24 09:10 UTC, eu-genia requested changes

2025-01-24 09:10 UTC, eu-genia commented on new/LIT6605JacobNat.xml
> +            <change who="DR" when="2023-05-24">Added bibliography provided by Aaron Butts</change>
@thea-m you may not merge this very old pull request as in the meanwhile the works starting with 6000 have all been moved to numbered folders, so merging this would create doublets. Please transfer the relevant changes to the master and close this one without merging. Thank you.

2025-05-19 10:21 UTC, eu-genia commented
have the changes been in the meanwhile merged to master?

2025-05-22 11:39 UTC, closed without merging